[package]
name = "syscraws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.9.0"
enum-iterator = "1.3.0"
num = "0.4.0"
